### ISSUE TITLE
add Service Monitor

### ISSUE THREAD

**Issue by vanhoutenbos** [k3rnelpan1c-dev/uptime-kuma-helm#125]
Hi,

It would be a nice feature to add a serviceMonitor to this chart so that when rolling out this monitor if added.
The user would only be in charge afterward to add a secret, since we need a token from the UI to expose the `/metrics` I dont think it is possible to create the token beforehand.

I would be available to create a PR for this if you are open to adding a Service Montitor!

**Comment by k3rnelpan1c-dev** [comment]
Hi there vanhoutenbos!

Your proposal sounds reasonable to me, provided it as a toggle locked feature (provided it requires a token first generated within kuma's UI).
I would highly welcome the contribution, provided you offered it :+1: (much obliged).

**Comment by vanhoutenbos** [comment]
I would love to add the creation of the secret from the values file but im not sure how that would work since the secret should stay a secret 🤔 
Also it is not possible to create the token from the deployment according to the documentation of kuma :(

**Comment by k3rnelpan1c-dev** [comment]
yeah, this is why I avoid including the Secret resource within my charts.
It invites suboptimal security practices, but sometimes there is no way past it.

Best solution I opt for usually is to have a configurable reference to an existing secret resource with configurable key reference. (at my job we use "external secrets" and being able to include this resource in charts is nice and only requires the secret present in our Hashicorp Vault at the location expected :wink: )

**Comment by k3rnelpan1c-dev** [comment]
It is indeed unfortunate that Kuma does not provide a way to generate a secret from outside the UI, or better an option to expose the metrics on a different port/endpoint with or without Auth, but the feature is relatively new as far as I can tell :thinking:

**Comment by k3rnelpan1c-dev** [comment]
released with `v1.1.0`, thank you for your contribution ;)
