### ISSUE TITLE
Add CommonLabels

### ISSUE THREAD

**Issue by vanhoutenbos** [k3rnelpan1c-dev/uptime-kuma-helm#126]
I use charts from bitnami quite a lot and one thing they have nailed down is adding a `commonLabels` value with labels that every resource uses, this could be a nice addition to this helm chart.

If this is somethng you like I could take the time to create a PR :D

**Comment by k3rnelpan1c-dev** [comment]
Would you have a sample as to what that would look like for this chart? (i.e. what label would you expect to be added to a resource by this chart)

> I use bitnami charts too, however, I cannot say I noticed any particular common labels (likely haven't had the need to dig down too deep, as these charts usually end up only in Dev/Test stages)

**Comment by vanhoutenbos** [comment]
Yes ofcourse!

At my current customer they use commonLabels like `group` and than the name of the helm chart to group them together for cleanup.
But they also add things like branch_name and git_hash to all resources to validate its from the same source.

We run uptime kuma all the way through the stages from test to production :D

**Comment by k3rnelpan1c-dev** [comment]
I see, but would that not be already possible by utilising the `.statefulSet.labels` object?
Or where you thinking of a "global" common labels object that gets merged in to every resource deployed by the chart?
I am not opposed to this idea, so if you want/have the spare time, then feel free to send me a PR :slightly_smiling_face:

**Comment by vanhoutenbos** [comment]
I was indeed thinking of a global label for all the resources not just the stateful and the pod, for example we use a namespace cleaner to keep our feature branches clean :)

**Comment by k3rnelpan1c-dev** [comment]
released with `v1.1.0`, thank you for your contribution ;)
