### ISSUE TITLE
New upstream versions

### ISSUE THREAD

**Issue by Yeradon** [k3rnelpan1c-dev/uptime-kuma-helm#158]
I noticed that the chart/ container, hasnt kept track with the latest upstream releases. Is there anything that stops this from happening?

**Comment by k3rnelpan1c-dev** [comment]
Hello there Yeradon

Sorry for the very late response!
I have been busy with IRL responsibilities for the past couple of weeks (mainly moving country) and been unable to merge the version bumps.
My apologies for any inconveniences that may have caused to you and anyone else using this Chart.

With stuff settling down, I will do my best to keep my target of keeping up with upstream within about 2 days of a release.

Thank you for reaching out and using this Chart!

**Comment by k3rnelpan1c-dev** [comment]
I merged all updates and released 1.3.4 of the Chart.
This now brings you right up to the latest `uptime-kuma`, `cloudflared` and `apprise` versions available.
Happy Uptime Monitoring!
