### ISSUE TITLE
Make the Helm Chart available through a Helm repository

### ISSUE THREAD

**Issue by dbluxo** [k3rnelpan1c-dev/uptime-kuma-helm#77]
Would be cool to be able to download/install the Helm Chart directly from GitHub's Helm repository: https://helm.sh/docs/howto/chart_releaser_action/

**Comment by k3rnelpan1c-dev** [comment]
Hi there!

While I understand the motivation why that would be nice to have I kind of shied away from doing it till now due to me not knowing if I want to host a single chart repository.
However, it is something that should not limit the ease of use for potential users, so it is something that should get integrated into the CI and automated. 
Not sure when I will pick this up, but, unless someone else wants to take a shot, I will do eventually.

**Comment by Xplouder** [comment]
@k3rnelpan1c-dev can you elaborate a bit more about this? Using github pages to create a helm registry is simple. 
Meanwhile can we have this repository versioned with tags/releases?

**Comment by k3rnelpan1c-dev** [comment]
I am aware it is straight forward and easy to set up, but I lack time lately to get around doing anything on my personal projects unfortunately :disappointed: 

In regards to tags, I am not opposed and can do that the next time I bump the chart.

**Comment by Xplouder** [comment]
@k3rnelpan1c-dev Sure, if you want i can create a PR to implement the helm registry. I just didn't proposed it because i felt from your initial comment that you could not host a single chart repository.

**Comment by k3rnelpan1c-dev** [comment]
Would appreciate that the help for sure!

Oh no, I was more on if I wanted to transform this repo to a multi chat repo or not, as that would imply a different setup requirement.
However, since I was never a fan of the idea (mono repo for x Charts) a setup for solely this chart is the way.

**Comment by hypery2k** [comment]
[artifacthub.io](https://artifacthub.io/) would be a good alternative. They offer the publishing of [helm charts](https://artifacthub.io/docs/topics/repositories/helm-charts/), too

**Comment by k3rnelpan1c-dev** [comment]
I may have some time the coming weekend to investigate this again, no promises nor ETA though.

**Comment by pat-s** [comment]
I'd also appreciate if a "proper" helm registry would be available. There are many actions that do this easily, with [helm chart releaser](https://github.com/helm/chart-releaser-action) being the most prominent one.

Currently I need to use `helm-git` to install from git directly as no helm repo is available. 
Also `renovate` complains about it then as `helm-git` based repos cannot be tracked

```
WARN: Package lookup failures (repository=$REPO)
       "warnings": [
         "Failed to look up helm package uptime-kuma"
``` 

If you want to change your monorepo appraoch at some point, you could just switch/update the install command in the README instructions.

**Comment by Xplouder** [comment]
@k3rnelpan1c-dev what about to use dockerhub as registry using OCI format?

**Comment by k3rnelpan1c-dev** [comment]
> @k3rnelpan1c-dev what about to use dockerhub as registry using OCI format?

OCI format of the Helm chart? I have considered that, even if it was not on DockerHub, however, the limiting factor, when I tried that, was that he resulting artifact would be colliding with the rootless container image I publish.

> I'd also appreciate if a "proper" helm registry would be available. There are many actions that do this easily, with [helm chart releaser](https://github.com/helm/chart-releaser-action) being the most prominent one.
> ...

I somehow haven't stumbled over this yet, arguable I haven't had the time to properly research this for quite a while (looking at the age of this issue).
That being said, this is probably the most promising suggestion that I want to give a try.
Thank you for pointing me toward it! :+1:

**Comment by k3rnelpan1c-dev** [comment]
well, after messing up the workflow twice :man_facepalming: this is now a thing.
I may toy around with the changelog feature of `chart-release` later, however, for now this is acceptable form my point of view.

Thank you again @pat-s for the pointer!

Unless anyone is opposed to it I will be closing this issue next week.

**Comment by Xplouder** [comment]
> > @k3rnelpan1c-dev what about to use dockerhub as registry using OCI format?
> 
> OCI format of the Helm chart? I have considered that, even if it was not on DockerHub, however, the limiting factor, when I tried that, was that he resulting artifact would be colliding with the rootless container image I publish.

Yes, you had to have a different registry. Bitnami have one for images (e.g [Redis](https://hub.docker.com/r/bitnami/redis)) and another for charts (e.g [Redis Chart](https://hub.docker.com/r/bitnamicharts/redis))

**Comment by k3rnelpan1c-dev** [comment]
I see, didn't know Bitnami published their charts in OCI format these days (next to their regular).
Good to know!

Regardless, I am not opposed to it, yet I would ask you to open a new request for this form of publishing, as I am considering this feature request done.

Thank you all who have chimed in and participated! Hope the new helm repository works for you and keep track of your uptime ;-)
